
import java.awt.Label;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yunuspektas
 */
public class SiparisUygulaması extends javax.swing.JFrame  {

    Map<String,Integer> siparisler = new LinkedHashMap<String,Integer>();
    // hash map ypaıyoruz çünkü eklenme sırasına göre kaydetmek için
    //Set<String> set = new LinkedHashSet<String>();
    //LinkedHashSet eklediğim şey daha  fazla eklenmesin diye böyle yaptık. 1 kere eklenir
    //ve sırayla eklenir
    //hashmapler programda seçtiğimiz sıraya göre eklenir
    
    
    
    
    public SiparisUygulaması() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iskender = new javax.swing.JCheckBox();
        beyti = new javax.swing.JCheckBox();
        salata = new javax.swing.JCheckBox();
        ayran = new javax.swing.JCheckBox();
        siparis_goster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sipariş Uygulaması");

        jLabel1.setText("MENÜ");

        iskender.setText("İskender - 150 TL");

        beyti.setText("Beyti - 120 TL ");

        salata.setText("Salata - 50 TL");

        ayran.setText("Ayran - 20 TL");

        siparis_goster.setText("Siparişleri Göster");
        siparis_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparis_gosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beyti)
                            .addComponent(ayran)
                            .addComponent(salata)
                            .addComponent(siparis_goster, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iskender)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(iskender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(beyti)
                .addGap(18, 18, 18)
                .addComponent(salata)
                .addGap(18, 18, 18)
                .addComponent(ayran)
                .addGap(18, 18, 18)
                .addComponent(siparis_goster)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void siparisleriGoster(){
        
        String message = "";
        int tutar = 0;
        
        if (siparisler.isEmpty()) { // eğer isEmpty boş mu diye kontrol eder boşsa true döner. hashmapi kontrol ettim
            message = "Siparişiniz Bulunmamaktadır.";
        }
        else{//mapim dolu demek
            
            message += "Siparişler\n";
            
            for(Map.Entry<String,Integer> entry : siparisler.entrySet() ){
                message += entry.getKey() + "\n"; //entry.getKey() ile string olan key ekledik
                tutar += entry.getValue();
            }
            //mapler direkt foreach döngüsüyle ekrana yazılamaz
            //biz mapimizi entrysete dönüştürmemiz gerekiyo  
              message += "Toplam Tutar : " + tutar;
        }
        
        JOptionPane.showMessageDialog(this, message); //JOptionPane.showMessageDialog ile ekrana mesaj dialogu bastırırız.
        // bastıracağımız mesaj kendi sınıfımızdan olacağı jframeizden için componente bu sınıf anlamında this yolluyoruz şu anki objemizi gösteriyoruz
        //yanına bastırmak istediğimiz mesajı yolluyoruz
        
        
        
        
        
    }
    
    private void siparis_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparis_gosterActionPerformed
        if (iskender.isSelected()) {//chechboxtaki isSelected seçilmişse anlamı var seçilmişse true döner seçilmemişse false döner
            //seçmesem bile yada tikini kaldırırsam false döner
            
            siparisler.put("İskender", 150);
            //aynı iskender bir daha eklenmesin diye hashmap kullandık
        }
        else{
            siparisler.remove("İskender");
        }
        
        if (beyti.isSelected()) {//chechboxtaki isSelected seçilmişse anlamı var seçilmişse true döner seçilmemişse false döner
            //seçmesem bile yada tikini kaldırırsam false döner
            
            siparisler.put("Beyti", 120);
            //aynı iskender bir daha eklenmesin diye hashmap kullandık
        }
        else{
            siparisler.remove("Beyti");
        }
        
        if (salata.isSelected()) {//chechboxtaki isSelected seçilmişse anlamı var seçilmişse true döner seçilmemişse false döner
            //seçmesem bile yada tikini kaldırırsam false döner
            
            siparisler.put("Salata", 50);
            //aynı iskender bir daha eklenmesin diye hashmap kullandık
        }
        else{
            siparisler.remove("Salata");
        }
        
        if (ayran.isSelected()) {//chechboxtaki isSelected seçilmişse anlamı var seçilmişse true döner seçilmemişse false döner
            //seçmesem bile yada tikini kaldırırsam false döner
            
            siparisler.put("Ayran", 20);
            //aynı iskender bir daha eklenmesin diye hashmap kullandık
        }
        else{
            siparisler.remove("Ayran");
        }
        
       
        siparisleriGoster();
        
    }//GEN-LAST:event_siparis_gosterActionPerformed

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisUygulaması().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayran;
    private javax.swing.JCheckBox beyti;
    private javax.swing.JCheckBox iskender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox salata;
    private javax.swing.JButton siparis_goster;
    // End of variables declaration//GEN-END:variables
}
